# Generated by Django 5.2.3 on 2025-06-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app_management', '0004_department_designation_teacherinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_app_management.designation'),
        ),
    ]
